repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    -   id: check-ast
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
-   repo: https://gitlab.com/PyCQA/flake8 
    rev: master
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/pylint
    rev: master
    hooks:
    -   id: pylint
