name: 'openpilot env setup, with retry on failure'

inputs:
  git_lfs:
    description: 'Whether or not to pull the git lfs'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - id: setup-1
      uses: ./.github/workflows/base_setup
      continue-on-error: true
      with:
        git_lfs: ${{ inputs.git_lfs }}
    - if: steps.setup-1.conclusion == 'failure'
      shell: bash
      run: sleep 30
    - id: setup-2
      if: steps.setup-1.conclusion == 'failure'
      uses: ./.github/workflows/base_setup
      continue-on-error: true
      with:
        git_lfs: ${{ inputs.git_lfs }}
    - if: steps.setup-2.conclusion == 'failure'
      shell: bash
      run: sleep 30
    - id: setup-3
      if: steps.setup-2.conclusion == 'failure'
      uses: ./.github/workflows/base_setup
      with:
        git_lfs: ${{ inputs.git_lfs }}