name: 'openpilot env setup, with retry on failure'

inputs:
  git_lfs:
    description: 'Whether or not to pull the git lfs'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - id: setup1
      uses: ./.github/workflows/base_setup
      with:
        git_lfs: ${{ inputs.git_lfs }}
    - if: failure() && steps.setup1.conclusion == 'failure'
      shell: bash
      run: sleep 30
    - id: setup2
      if: failure() && steps.setup1.conclusion == 'failure'
      uses: ./.github/workflows/base_setup
      with:
        git_lfs: ${{ inputs.git_lfs }}
    - if: failure() && steps.setup2.conclusion == 'failure'
      shell: bash
      run: sleep 30
    - id: setup-3
      if: failure() && steps.setup2.conclusion == 'failure'
      uses: ./.github/workflows/base_setup
      with:
        git_lfs: ${{ inputs.git_lfs }}