name: Bug report
description: For issues with running zenpilot on your comma device
labels: ["bug"]
body:

  - type: markdown
    attributes:
      value: >
        Before creating a **bug report**, please check the following:
          * The issue is directly related to one of the features this fork has added
          * Ensure you're running the latest zenpilot release.
          * If the issue is related to the driving or driver monitoring models, you should open a [discussion](https://github.com/commaai/openpilot/discussions/categories/model-feedback) over on openpilot.

        If you're unsure whether you've hit a bug, mention syberdelicWolf on #custom-forks channel in the [community Discord server](https://discord.comma.ai).

  - type: textarea
    attributes:
      label: Describe the bug
      description: Also include a description of how to reproduce the bug
    validations:
      required: true

  - type: input
    id: route
    attributes:
      label: Provide a route where the issue occurs
      description: Ensure the route is fully uploaded at https://useradmin.comma.ai. We cannot look into issues without routes, or at least a Dongle ID.
      placeholder: 77611a1fac303767|2020-05-11--16-37-07
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: zenpilot version
      description: If you're not on release, provide the commit hash
      placeholder: 0-23.JAN.18-ZP-0.9.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional info

