blank_issues_enabled: false
contact_links:
  - name: Report model bugs
    url: https://github.com/commaai/openpilot/discussions?discussions_q=label%3Adrivingfb
    about: Provide feedback for the driving or driver monitoring models
  - name: Discussions
    url: https://github.com/commaai/openpilot/discussions
    about: For questions and general discussion about openpilot
  - name: Community Wiki
    url: https://github.com/commaai/openpilot/wiki
    about: Check out our community wiki
  - name: Community Discord
    url: https://discord.comma.ai
    about: Check out our community discord
