name: 'openpilot env setup, with retry on failure'

inputs:
  sleep_time:
    description: 'Time to sleep between retries'
    required: false
    default: 30

jobs:
setup:
  runs-on: ubuntu-20.04
  steps:
    - id: setup1
      uses: ./.github/workflows/setup.yaml
      continue-on-error: true
      with:
        is_retried: true

    - name: Wait after first failure
      if: steps.setup1.outcome == 'failure'
      run: sleep ${{ inputs.sleep_time }}
      shell: bash

    - id: setup2
      if: steps.setup1.outcome == 'failure'
      uses: ./.github/workflows/setup.yaml
      continue-on-error: true
      with:
        is_retried: true

    - name: Wait after second failure
      if: steps.setup2.outcome == 'failure'
      run: sleep ${{ inputs.sleep_time }}
      shell: bash

    - id: setup3
      if: steps.setup2.outcome == 'failure'
      uses: ./.github/workflows/setup.yaml
      with:
        is_retried: true