name: 'openpilot env setup, with retry on failure'
on: [push, workflow_dispatch]
jobs:
  setup:
    runs-on: ubuntu-20.04-64core
    steps:
      - id: setup1
        uses: ./.github/workflows/setup
        continue-on-error: true
        with:
          is_retried: true

      - if: steps.setup1.outcome == 'failure'
        shell: bash
        run: sleep ${{ inputs.sleep_time }}

      - id: setup2
        if: steps.setup1.outcome == 'failure'
        uses: ./.github/workflows/setup
        continue-on-error: true
        with:
          is_retried: true

      - if: steps.setup2.outcome == 'failure'
        shell: bash
        run: sleep ${{ inputs.sleep_time }}

      - id: setup3
        if: steps.setup2.outcome == 'failure'
        uses: ./.github/workflows/setup
        with:
          is_retried: true
