name: 'openpilot env setup, with retry on failure'

inputs:
  docker_hub_pat:
    description: 'Auth token for Docker Hub, required for BuildJet jobs'
    required: false
    default: ''
  sleep_time:
    description: 'Time to sleep between retries'
    required: false
    default: 30

runs:
  using: "composite"
  steps:
    - id: setup1
      uses: ./.github/workflows/setup
      with:
        docker_hub_pat: ${{ inputs.docker_hub_pat }}
        is_retried: true

