name: 'build openpilot and test caching by relative path'

runs: 
  using: "composite"
  steps:
    - id: build_openpilot
      shell: bash
      run: |
        {
        echo 'BUILD_LOG<<EOF'
        ${{ env.RUN }} "scons -j$(nproc) --cache-show --warn=all"
        echo EOF
        } >> $GITHUB_OUTPUT
    - name: check if cached by relative path
      shell: bash
      run: |
        echo "${{ steps.build_openpilot.outputs.BUILD_LOG }}" >> $GITHUB_WORKSPACE/output.txt
        ${{ env.RUN }} "python3 scripts/test_relcache.py output.txt '${{ env.WORKSPACE }}'"
        rm $GITHUB_WORKSPACE/output.txt
