CHEVROLET VOLT PREMIER 2017: [438.0, 2.67, 0.0, 2120.0, -83.0, -1.62, 0.0, 24.4]
legend: [GAS_ACCEL_FACTOR, GAS_VEGO_FACTOR, GAS_PITCH_FACTOR, GAS_OFFSET, BRAKE_ACCEL_FACTOR, BRAKE_VEGO_FACTOR, BRAKE_PITCH_FACTOR, BRAKE_OFFSET]
