CHEVROLET VOLT PREMIER 2017: [484.0, 2.7, 4850.0, 2110.0, -83.9, -1.69, -264.0, 20.3]
legend: [GAS_ACCEL_FACTOR, GAS_VEGO_FACTOR, GAS_PITCH_FACTOR, GAS_OFFSET, BRAKE_ACCEL_FACTOR, BRAKE_VEGO_FACTOR, BRAKE_PITCH_FACTOR, BRAKE_OFFSET]
