CHEVROLET VOLT PREMIER 2017: [352.0, 4.31, 5140.0, 2070.0, -85.6, -0.708, -246.0, 15.7]
legend: [GAS_ACCEL_FACTOR, GAS_VEGO_FACTOR, GAS_PITCH_FACTOR, GAS_OFFSET, BRAKE_ACCEL_FACTOR, BRAKE_VEGO_FACTOR, BRAKE_PITCH_FACTOR, BRAKE_OFFSET]
