legend: [GAS_ACCEL_FACTOR, GAS_VEGO_FACTOR, GAS_PITCH_FACTOR, GAS_OFFSET, BRAKE_ACCEL_FACTOR, BRAKE_VEGO_FACTOR, BRAKE_PITCH_FACTOR, BRAKE_OFFSET]
CHEVROLET VOLT PREMIER 2017: [483., 2.7, 4852., 2107., -84., -1.7, -264., 20.]
