CHEVROLET VOLT PREMIER 2017: [484.0, 2.63, 4930.0, 2110.0, -84.1, -1.7, -255.0, 20.5]
legend: [GAS_ACCEL_FACTOR, GAS_VEGO_FACTOR, GAS_PITCH_FACTOR, GAS_OFFSET, BRAKE_ACCEL_FACTOR, BRAKE_VEGO_FACTOR, BRAKE_PITCH_FACTOR, BRAKE_OFFSET]
