site_name: openpilot docs
docs_dir: docs

theme:
  name: terminal
  features:
    - navigation.side.toc.hide

nav:
  - Getting Started:
      - What is openpilot?: getting-started/what-is-openpilot.md
  - Guides:
      - Turning the speed blue: guides/turning-the-speed-blue.md
  - Car Porting:
      - What is a car port?: car-porting/what-is-a-car-port.md
      - Porting a car brand: car-porting/brand-port.md
      - Porting a car model: car-porting/model-port.md
