name: weekly CI test run
on:
  workflow_call:
    inputs:
      run_number:
        required: true
        type: string

concurrency:
  group: ci-run-${{ inputs.run_number }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  value_print:
    runs-on: ubuntu-latest

    steps:
      - name: Print the ci_run value to STDOUT
        run: echo The ci_run value is ${{ inputs.run_number }}
  docs:
    uses: BBBmau/openpilot/.github/workflows/docs.yaml@master
    with:
      run_number: ${{ inputs.run_number }}
  selfdrive_tests:
    uses: BBBmau/openpilot/.github/workflows/selfdrive_tests.yaml@master
    with:
      run_number: ${{ inputs.run_number }}
  tools_tests:
    uses: BBBmau/openpilot/.github/workflows/tools_tests.yaml@master
    with:
      run_number: ${{ inputs.run_number }}
  badges:
    uses: BBBmau/openpilot/.github/workflows/badges.yaml@master
    with:
      run_number: ${{ inputs.run_number }}
  passing_check:
    needs: [ docs, selfdrive_tests, tools_tests, badges]
    if: contains(join(needs.*.result, ','), 'success')
    run: echo "PASSING_RUNS=$((${{ env.PASSING_RUNS }}+1))" >> $GITHUB_ENV
