name: weekly CI test report
on:
  schedule:
    - cron: '37 9 * * 1' # 9:37AM UTC -> 2:37AM PST every monday
  workflow_dispatch:
    inputs:
      ci_runs:
        default: 100
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  passing_tests: 0

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      ci_runs: ${{ steps.ci_runs_setup.outputs.value }}
    steps:
      - id: ci_runs_setup
        run: |
          mylist="value=["

          for i in $(seq 1 ${{ inputs.ci_runs }});
          do
              if [ $i != ${{ inputs.ci_runs }} ]; then
                  mylist+="\"$i\", "
              else
                  mylist+="\"$i\""
              fi
          done
          mylist+="]"

          echo "$mylist" >> $GITHUB_OUTPUT
      - run: |
          echo "Number of CI runs for report: ${{ inputs.ci_runs }}"
  ci_matrix_run:
    needs: [ setup ]
    uses: BBBmau/openpilot/.github/workflows/ci_weekly_run.yaml@master
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.ci_runs)}}
  results:
      if: ${{ always() }}
      runs-on: ubuntu-latest
      name: Final Results
      needs: [ci_matrix_run]
      steps:
        - run: |
            result="${{ needs.ci_matrix_run.result }}"
            if [[ $result == "success" || $result == "skipped" ]]; then
              exit 0
            else
              exit 1
            fi

