name: weekly CI test run
on:
  workflow_call:
    inputs:
      run_number:
        required: true
        type: string

concurrency:
  group: ci-run-${{ inputs.run_number }}-${{ github.ref }}

jobs:
  value_print:
    runs-on: ubuntu-latest

    steps:
      - name: Print the ci_run value to STDOUT
        run: echo The ci_run value is ${{ inputs.run_number }}
  docs:
    uses: BBBmau/openpilot/.github/workflows/docs.yaml@master
  selfdrive_tests:
    uses: BBBmau/openpilot/.github/workflows/selfdrive_tests.yaml@master
  tools_tests:
    uses: BBBmau/openpilot/.github/workflows/tools_tests.yaml@master
  badges:
    uses: BBBmau/openpilot/.github/workflows/badges.yaml@master