name: development tools
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  devcontainer:
    name: test dev container
    runs-on: ubuntu-latest
    if: github.repository == 'commaai/openpilot'
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup Dev Container CLI
      run: npm install -g @devcontainers/cli
    - name: Build dev container image
      run: devcontainer build --workspace-folder .
    - name: Run dev container
      run: devcontainer up --workspace-folder .
    - name: Stop containers
      run: docker kill $(docker ps -q)
