name: docs

on:
  push:
    branch:
      - master
  pull_request:

concurrency:
  group: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.run_id || github.head_ref || github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: 3.11
  APT_PACKAGES: autoconf build-essential ca-certificates casync clang cmake make cppcheck libtool gcc-arm-none-eabi bzip2 liblzma-dev libarchive-dev libbz2-dev capnproto libcapnp-dev curl libcurl4-openssl-dev git git-lfs ffmpeg libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev  libavfilter-dev libeigen3-dev libffi-dev libglew-dev libgles2-mesa-dev libglfw3-dev libglib2.0-0 libncurses5-dev libncursesw5-dev libomp-dev libopencv-dev libpng16-16 libportaudio2 libssl-dev libsqlite3-dev libusb-1.0-0-dev libzmq3-dev libsystemd-dev  locales opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev clinfo portaudio19-dev qml-module-qtquick2 qtmultimedia5-dev qtlocation5-dev qtpositioning5-dev qttools5-dev-tools libqt5sql5-sqlite libqt5svg5-dev libqt5charts5-dev libqt5serialbus5-dev  libqt5x11extras5-dev libreadline-dev libdw1 xvfb valgrind libavresample-dev qt5-default python-dev

jobs:
  docs:
    name: build docs
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: ./.github/workflows/setup-with-retry-new
    - name: Build openpilot
      run: python -m poetry run scons -j$(nproc)
    - name: Build docs
      run: bash -i -c "sudo apt update && sudo apt install -y doxygen && cd docs && python -m poetry run make -j$(nproc) html"

    - uses: actions/checkout@v4
      if: github.ref == 'refs/heads/master' && github.repository == 'commaai/openpilot'
      with:
        path: openpilot-docs
        ssh-key: ${{ secrets.OPENPILOT_DOCS_KEY }}
        repository: commaai/openpilot-docs
    - name: Push
      if: github.ref == 'refs/heads/master' && github.repository == 'commaai/openpilot'
      run: |
        set -x

        source release/identity.sh

        cd openpilot-docs

        git checkout --orphan tmp
        git rm -rf .

        cp -r ../build/docs/html/ docs/
        cp -r ../docs/README.md .
        touch docs/.nojekyll
        echo -n docs.comma.ai > docs/CNAME
        git add -f .

        git commit -m "build docs"

        # docs live in different repo to not bloat openpilot's full clone size
        git push -f origin tmp:gh-pages
