name: fingerprint bot

on:
  issue_comment:                                     
    types: [created, edited]

env:
  BUILD: selfdrive/test/docker_build.sh base
  RUN: docker run --shm-size 1G -v $PWD:/tmp/openpilot -w /tmp/openpilot -e PYTHONWARNINGS=error -e FILEREADER_CACHE=1 -e PYTHONPATH=/tmp/openpilot -e NUM_JOBS -e JOB_ID -e GITHUB_ACTION -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e COMMENT_BODY -e GITHUB_OUTPUT -v $GITHUB_OUTPUT:$GITHUB_OUTPUT -v $GITHUB_WORKSPACE/.ci_cache/scons_cache:/tmp/scons_cache -v $GITHUB_WORKSPACE/.ci_cache/comma_download_cache:/tmp/comma_download_cache -v $GITHUB_WORKSPACE/.ci_cache/openpilot_cache:/tmp/openpilot_cache $BASE_IMAGE /bin/sh -c
  BASE_IMAGE: openpilot-base

jobs:
  fingerprint:
    if: contains(github.event.comment.body, '/fingerprint')
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/workflows/setup-with-retry
      - name: Build openpilot
        timeout-minutes: ${{ ((steps.restore-scons-cache.outputs.cache-hit == 'true') && 10 || 30) }} # allow more time when we missed the scons cache
        run: ${{ env.RUN }} "scons -j$(nproc)"
      - name: fingerprint
        id: fingerprint
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          ${{ env.RUN }} "python selfdrive/debug/ci_fingerprint.py"
      - name: create branch
        run: |
          git config --global user.email "fingerprint-researcher@comma.ai"
          git config --global user.name "Fingerprint Researcher"
          git switch -c ${{ steps.fingerprint.outputs.pr-branch-name }}
          git add .
          git commit -m '${{ steps.fingerprint.outputs.pr-title }}'
          git push -u origin ${{ steps.fingerprint.outputs.pr-branch-name }}
      - name: create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create -B master -H ${{ steps.fingerprint.outputs.pr-branch-name }} --title '${{ steps.fingerprint.outputs.pr-title }}' --body '${{ steps.fingerprint.outputs.pr-comment }}'