name: "Pull Request Labeler"
on:
  push:

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    - uses: actions/labeler@v5.0.0-alpha.1
      with:
#        dot: true
        sync-labels: true
        configuration-path: .github/labeler.yaml
    - id: print-labels
      if: always()
      run: |
        echo "added labels: ${{ steps.labeler.outputs.added-labels }}"
