name: "PR review"
on:
  pull_request_target:

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    - uses: actions/labeler@v5.0.0-alpha.1
      with:
        dot: true
        configuration-path: .github/labeler.yaml

  comment:
    runs-on: ubuntu-latest
    steps:
      - name: comment
        uses: thollander/actions-comment-pull-request@1d3973dc4b8e1399c0620d3f2b1aa5e795465308
        with:
          message: |
              Thank you for your contribution. We will review as soon as we're able to.

              Remember to check the [contributing docs](https://github.com/commaai/openpilot/blob/master/docs/CONTRIBUTING.md).
          comment_includes: "Thank you"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}