name: "Pull Request Labeler"
on:
  pull_request_target:

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    - uses: actions/labeler@v5.0.0-alpha.1
      with:
        dot: true
        configuration-path: .github/labeler.yaml

  pr_branch_check:
    runs-on: ubuntu-latest
    if: github.repository == 'maxime-desroches/openpilot'
    steps:
    - uses: Vankka/pr-target-branch-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        target: /^(?!master$).*/
        exclude: /maxime-desroches:.*/
        change-to: ${{ github.base_ref }}
        already-exists-action: close_this
        already-exists-comment: "Your PR should be made against the `master` branch"
