name: Bot Review

on:
  pull_request:
    types:
      - opened
      - edited
jobs:
  bot_review:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install PyGithub requests

      - name: Run Bot Review
        run: python scripts/review_bot.py "${{ github.event_path }}"


