name: prebuilt
on:
  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

env:
  BASE_IMAGE: openpilot-base
  DOCKER_REGISTRY: ghcr.io/commaai

  DOCKER_LOGIN: docker login ghcr.io -u adeebshihadeh -p ${{ secrets.CONTAINER_TOKEN }}
  BUILD: |
      docker pull $(grep -iohP '(?<=^from)\s+\S+' Dockerfile.openpilot_base) || true
      docker pull $DOCKER_REGISTRY/$BASE_IMAGE:latest || true
      docker build --cache-from $DOCKER_REGISTRY/$BASE_IMAGE:latest -t $DOCKER_REGISTRY/$BASE_IMAGE:latest -t $BASE_IMAGE:latest -f Dockerfile.openpilot_base .

jobs:
  skip_duplicate:
    name: build prebuilt
    runs-on: ubuntu-20.04
    if: github.repository == 'commaai/openpilot'
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@9d116fa7e55f295019cfab7e3ab72b478bcf7fdd

  build_prebuilt:
    name: build prebuilt
    runs-on: ubuntu-20.04
    needs: skip_duplicate
    timeout-minutes: 60
    if: github.repository == 'commaai/openpilot' && ${{ needs.pre_job.outputs.should_skip != 'true' }}
    env:
      IMAGE_NAME: openpilot-prebuilt
    steps:
    - name: Skip duplicate build prebuilt
      uses: fkirc/skip-duplicate-actions@v4.0.0
    - name: Wait for green check mark
      uses: commaai/wait-on-check-action@f16fc3bb6cd4886520b4e9328db1d42104d5cadc
      with:
        ref: master
        wait-interval: 30
        running-workflow-name: 'build prebuilt'
        check-regexp: ^((?!.*(build master-ci).*).)*$
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build Docker image
      run: |
        eval "$BUILD"
        docker pull $DOCKER_REGISTRY/$IMAGE_NAME:latest || true
        docker build --cache-from $DOCKER_REGISTRY/$IMAGE_NAME:latest -t $DOCKER_REGISTRY/$IMAGE_NAME:latest -f Dockerfile.openpilot .
    - name: Push to container registry
      run: |
        $DOCKER_LOGIN
        docker push $DOCKER_REGISTRY/$IMAGE_NAME:latest
