name: release
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build_experimental:
    name: build experimental
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    if: github.repository == 'chadgauth/zenpilot'
    steps:
    - name: Wait for green check mark
      uses: lewagon/wait-on-check-action@e2558238c09778af25867eb5de5a3ce4bbae3dcd
      with:
        ref: develop
        wait-interval: 30
        running-workflow-name: 'build experimental'
        check-regexp: ^((?!.*(build prebuilt).*).)*$
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    - name: Pull LFS
      run: git lfs pull
    - name: Build experimental
      run: |
        BRANCH=experimental release/build_devel.sh
