name: release
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build_experimental:
    name: build experimental
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    if: github.repository == 'chadgauth/zenpilot'
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    - name: Pull LFS
      run: git lfs pull
    - name: Build experimental
      run: |
        BRANCH=experimental release/build_devel.sh
