name: release
on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build_experimental:
    name: build experimental
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    if: github.repository == 'chadgauth/zenpilot'
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    - name: Pull LFS
      run: git lfs pull
    - name: Build experimental
      run: |
        BRANCH=experimental release/build_devel.sh
