on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - run: |
        docker build -t tmppilot -f Dockerfile.openpilot .
        docker save tmppilot:latest | gzip > tmppilot.tar.gz
    - uses: actions/upload-artifact@v1
      with:
        name: tmppilot.tar.gz
        path: tmppilot.tar.gz

  linter:
    name: linter
    runs-on: ubuntu-16.04
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: tmppilot.tar.gz
      - name: Load image
        run: docker load -i tmppilot.tar.gz/tmppilot.tar.gz
      - name: flake8
        run: docker run --shm-size 1G --rm tmppilot /bin/sh -c "cd /tmp/openpilot/ && ./flake8_openilot.sh"
      - name: pylint
        run: docker run --shm-size 1G --rm tmppilot /bin/sh -c "cd /tmp/openpilot/ && ./pylint.sh"

#  unit_tests:
#    name: unit tests
#    runs-on: ubuntu-16.04
#    needs: build
#    - uses: actions/download-artifact@v1
#      with:
#        name: tmppilot.tar.gz
#    - run: docker load -i tmppilot.tar.gz/tmppilot.tar.gz
#    container: tmppilot
#    steps:
#      - run: |
#          cd /tmp/openpilot
#
#          python -m unittest discover common
#          python -m unittest discover opendbc/can
#          python -m unittest discover selfdrive/boardd
#          python -m unittest discover selfdrive/controls
#          python -m unittest discover selfdrive/loggerd
#          python -m unittest discover selfdrive/car
#          python -m unittest discover selfdrive/locationd

