on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - run: |
        docker build -t tmppilot -f Dockerfile.openpilot .
        docker save tmppilot:latest | gzip > tmppilot.tar.gz
    - uses: actions/upload-artifact@v1
      with:
        name: tmppilot.tar.gz
        path: tmppilot.tar.gz

  linter:
    name: linter
    runs-on: ubuntu-16.04
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: tmppilot.tar.gz
      - name: Load image
        run: docker load -i tmppilot.tar.gz/tmppilot.tar.gz
      - name: flake8
        run: docker run --shm-size 1G --rm tmppilot /bin/sh -c "cd /tmp/openpilot/ && ./flake8_openpilot.sh"
      - name: pylint
        run: docker run --shm-size 1G --rm tmppilot /bin/sh -c "cd /tmp/openpilot/ && ./pylint_openpilot.sh"

  unit_tests:
    name: unit tests
    runs-on: ubuntu-16.04
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: tmppilot.tar.gz
      - name: Load image
        run: docker load -i tmppilot.tar.gz/tmppilot.tar.gz
      - name: Run unit tests
        run: |
          docker run --shm-size 1G --rm tmppilot /bin/sh -c "cd /tmp/openpilot && python -m unittest discover common"
          docker run --shm-size 1G --rm tmppilot /bin/sh -c "cd /tmp/openpilot && python -m unittest discover opendbc/can"
          docker run --shm-size 1G --rm tmppilot /bin/sh -c "cd /tmp/openpilot && python -m unittest discover selfdrive/boardd"
          docker run --shm-size 1G --rm tmppilot /bin/sh -c "cd /tmp/openpilot && python -m unittest discover selfdrive/controls"
          docker run --shm-size 1G --rm tmppilot /bin/sh -c "cd /tmp/openpilot && python -m unittest discover selfdrive/loggerd"
          docker run --shm-size 1G --rm tmppilot /bin/sh -c "cd /tmp/openpilot && python -m unittest discover selfdrive/car"
          docker run --shm-size 1G --rm tmppilot /bin/sh -c "cd /tmp/openpilot && python -m unittest discover selfdrive/locationd"
          docker run --shm-size 1G --rm tmppilot /bin/sh -c "cd /tmp/openpilot && python -m unittest discover selfdrive/athena"

  process_replay:
    name: process replay
    runs-on: ubuntu-16.04
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: tmppilot.tar.gz
      - name: Load image
        run: docker load -i tmppilot.tar.gz/tmppilot.tar.gz
      - name: Replay processes
        run: docker run --shm-size 1G --rm tmppilot /bin/sh -c "cd /tmp/openpilot/selfdrive/test/process_replay && CI=1 ./test_processes.py"

  test_car_models:
    name: test car models
    runs-on: ubuntu-16.04
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: tmppilot.tar.gz
      - name: Load image
        run: docker load -i tmppilot.tar.gz/tmppilot.tar.gz
      - name: Test car models
        run: docker run --shm-size 1G --rm tmppilot /bin/sh -c "mkdir -p /data/params && cd /tmp/openpilot/selfdrive/test/ && ./test_car_models.py"

  test_longitudinal:
    name: longitudinal
    runs-on: ubuntu-16.04
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: tmppilot.tar.gz
      - name: Load image
        run: docker load -i tmppilot.tar.gz/tmppilot.tar.gz
      - name: Test Longitudinal
        run: docker run --shm-size 1G --rm tmppilot /bin/sh -c "cd /tmp/openpilot/selfdrive/test/longitudinal_maneuvers && OPTEST=1 ./test_longitudinal.py"

