name: openpilot tests
on:
  push:
  pull_request:

env:
  RUN: docker run --shm-size 1G --rm tmppilot /bin/sh -c
  RUN_WEBCAM: docker run --shm-size 1G --rm tmppilotwebcam /bin/sh -c
  PERSIST_WITH_CACHE: docker run --shm-size 1G -v /tmp/comma_download_cache:/tmp/comma_download_cache  --name tmppilot tmppilot /bin/sh -c
  PERSIST: docker run --shm-size 1G --name tmppilot tmppilot /bin/sh -c
  CI_RUN: docker run -e GITHUB_ACTION -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID --rm tmppilotci /bin/bash -c
  UNIT_TEST: coverage run --append -m unittest discover
  BUILD_BASE: |
      docker pull $(grep -ioP '(?<=^from)\s+\S+' Dockerfile.openpilot_base) || true
      docker pull docker.io/commaai/openpilot-base:latest || true
      docker build --cache-from docker.io/commaai/openpilot-base:latest -t commaai/openpilot-base:latest -f Dockerfile.openpilot_base .
  BUILD: |
      eval "$BUILD_BASE"
      docker pull docker.io/commaai/openpilotci:latest || true
      docker build --cache-from docker.io/commaai/openpilotci:latest -t tmppilot -f Dockerfile.openpilotci .
  BUILD_WEBCAM: |
      eval "$BUILD"
      docker build --cache-from docker.io/commaai/openpilotwebcamci:latest -t tmppilotwebcam -f tools/webcam/Dockerfile .


jobs:

  docker_push:
    name: docker push
    runs-on: ubuntu-16.04
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Docker image
        run: eval "$BUILD_WEBCAM"
      - name: Push to dockerhub
        run: |
          docker login -u wmelching -p ${{ secrets.COMMA_DOCKERHUB_TOKEN}}
          docker tag commaai/openpilot-base:latest docker.io/commaai/openpilot-base:latest
          docker push docker.io/commaai/openpilot-base:latest
          docker tag tmppilot docker.io/commaai/openpilotci:latest
          docker push docker.io/commaai/openpilotci:latest
          docker tag tmppilotwebcam docker.io/commaai/openpilotwebcamci:latest
          docker push docker.io/commaai/openpilotwebcamci:latest

