name: "Update Pipfile.lock"
on: push # just for testing, to be removed
# on: '00 08 * * 1' # Every monday on 08:00 UTC

jobs:
  piplock:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install wheel pipenv
    - run: pipenv lock --requirements
    - uses: actions/upload-artifact@v2
      with:
        name: "Pipfile lock"
        path: Pipfile.lock
    - uses: peter-evans/create-pull-request@v2
      with:
        title: "Update Pipfile.lock (dependencies)"
        branch: update-pipfile
